# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiHID0oEis5-a2pWD6o23LgACSmJgmqF

**Task 08: Completing missing data**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

from rdflib.plugins.sparql import prepareQuery
from rdflib.namespace import RDF, RDFS
do = Namespace("http://data.one.org#")
vcard=Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")

q1 = prepareQuery('''
  SELECT ?Sujeto WHERE {

    ?Sujeto rdf:type ?Clase.
    ?Clase rdf:type rdfs:Class
  }
  order by ?Sujeto
  ''',
  initNs = { "do": do , "rdf": RDF ,"rdfs": RDFS ,"vcard": vcard }
)

print('**============== SPARQL ')
for r in g1.query(q1):
  print(r.Sujeto)

vcard=Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
for t2 in g2:

  if t2[1] in [vcard.Given , vcard.EMAIL , vcard.Family]:
    print(t2)

# Recorremos el grafo 2 y vamos añadiendo las tres propiedades
from rdflib.plugins.sparql import prepareQuery
from rdflib.namespace import RDF, RDFS
do = Namespace("http://data.one.org#")
vcard=Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

for s, p, o in g2:
  if p in [vcard.Given , vcard.EMAIL , vcard.Family]:
    g1.add((s, p, o))

# Comprobamos el resultado
from rdflib.plugins.sparql import prepareQuery
from rdflib.namespace import RDF, RDFS
do = Namespace("http://data.one.org#")
vcard=Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

for t1 in g1:
  if t1[1] in [vcard.Given , vcard.EMAIL , vcard.Family]:
    print(t1)

"""

---

"""